apps/novy_web/lib/novy_web/router.ex
defmodule NovyWeb.Router do
  use NovyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NovyWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NovyWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show

    
    live "/videos", VideoLive.Index, session: [:user_id]
    live "/videos/:id", VideoLive.Show
    live "/videos/new", VideoLive.New
    live "/videos/:id/edit", VideoLive.Edit
  end

  scope "/manage", NovyWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", NovyWeb do
  #   pipe_through :api
  # end
end

apps/novy_web/lib/novy_web/controllers/video_controller.ex
defmodule NovyWeb.VideoController do
  use NovyWeb, :controller

  alias Novy.Multimedia
  alias Novy.Multimedia.Video

  plug :load_categories when action in [:new, :create, :edit, :update]

  def index(conn, _params, current_user) do
    IO.inspect(current_user)
    videos = Multimedia.list_user_videos(current_user)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, _current_user) do
    changeset = Multimedia.change_video(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, current_user) do
    case Multimedia.create_video(current_user, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)
    changeset = Multimedia.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)

    case Multimedia.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    video = Multimedia.get_user_video!(current_user, id)
    {:ok, _video} = Multimedia.delete_video(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: Routes.video_path(conn, :index))
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  defp load_categories(conn, _) do
    assign(conn, :categories, Multimedia.list_alphabetical_categories())
  end
end

apps/novy_web/lib/novy_web/live/video/video_live.ex
defmodule NovyWeb.VideoLive.Index do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <label>Counter: <%= @counter %></label>
    <button phx-click="incr">+</button>
    <button phx-click="decr">-</button>
    """
  end

  def mount(_session, socket) do
    socket =
      socket
      |> assign(:counter, 0)
      |> IO.inspect()

    {:ok, socket}
  end

  def handle_event("incr", _event, socket) do
    socket = update(socket, :counter, &(&1 + 1))
    {:noreply, socket}
  end

  def handle_event("decr", _event, socket) do
    socket = update(socket, :counter, &(&1 - 1))
    {:noreply, socket}
  end
end

apps/novy_web/lib/novy_web/live/video/video_live_index.ex
defmodule NovyWeb.VideoLive.Index do
  use Phoenix.LiveView

  alias Novy.Multimedia
  alias Novy.Multimedia.Video
  
  def render(assigns) do
    ~L"""
    <h1>Listing Videos</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for video <- @videos do %>
          <tr>
            <td><%= video.title %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    """
  end

  def mount(%{user_id: user_id}, socket) do
    videos = Multimedia.list_user_videos(user_id)
    socket =
      socket
      |> assign(:videos, videos)
      |> IO.inspect()

    {:ok, socket}
  end

  def handle_event("incr", _event, socket) do
    socket = update(socket, :counter, &(&1 + 1))
    {:noreply, socket}
  end

  def handle_event("decr", _event, socket) do
    socket = update(socket, :counter, &(&1 - 1))
    {:noreply, socket}
  end
end

apps/novy_web/lib/novy_web/live/video/video_live_show.ex
defmodule NovyWeb.VideoLive.Show do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <label>Counter: <%= @counter %></label>
    <button phx-click="incr">+</button>
    <button phx-click="decr">-</button>
    """
  end

  def mount(_session, socket) do
    socket =
      socket
      |> assign(:counter, 0)
      |> IO.inspect()

    {:ok, socket}
  end

  def handle_event("incr", _event, socket) do
    socket = update(socket, :counter, &(&1 + 1))
    {:noreply, socket}
  end

  def handle_event("decr", _event, socket) do
    socket = update(socket, :counter, &(&1 - 1))
    {:noreply, socket}
  end
end

apps/novy_web/lib/novy_web/views/video_view.ex
defmodule NovyWeb.VideoView do
  use NovyWeb, :view

  alias UserLiveviewWeb.UserLive

  def category_select_options(categories) do
    for category <- categories, do: {category.name, category.id}
  end
end

apps/novy_web/lib/novy_web/templates/video/edit.html.eex
<h1>Edit Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

apps/novy_web/lib/novy_web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :url %>
  <%= text_input f, :url %>
  <%= error_tag f, :url %>

  <%= label f, :category_id, "Category" %>
  <%= select f, :category_id, category_select_options(@categories), prompt: "Choose a category" %>
  <%= error_tag f, :category_id %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

apps/novy_web/lib/novy_web/templates/video/index.html.eex
<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for video <- @videos do %>
      <tr>
        <td><%= video.title %></td>
        <td>
          <%= link "Edit", to: Routes.video_path(@conn, :edit, video) %>
        </td>
        <td>
          <%= link "Delete", to: Routes.video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"] %>
        </td>
        <td>
          <%= link "Watch", to: Routes.watch_path(@conn, :show, "#{video.id}-#{video.slug}"), class: "button" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "New Video", to: Routes.video_path(@conn, :new) %></span>

apps/novy_web/lib/novy_web/templates/video/new.html.eex
<h1>New Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

apps/novy_web/lib/novy_web/templates/video/show.html.eex
<h1>Show Video</h1>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>