apps/novy_web/lib/novy_web/router.ex
defmodule NovyWeb.Router do
  use NovyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NovyWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NovyWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show

    
    live "/videos", VideoLive.Index, session: [:user_id]
    live "/videos/:id", VideoLive.Show
    live "/videos/new", VideoLive.New
    live "/videos/:id/edit", VideoLive.Edit
  end

  scope "/manage", NovyWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", NovyWeb do
  #   pipe_through :api
  # end
end

apps/novy_web/lib/novy_web/views/layout_view.ex
defmodule NovyWeb.LayoutView do
  use NovyWeb, :view
end

apps/novy_web/lib/novy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Novy · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li><%= @current_user.username %></li>
              <li><%= link "My Videos", to: Routes.video_path(@conn, :index) %></li>
              <li>
                <%= link "Log out",
                      to: Routes.session_path(@conn, :delete, @current_user),
                      method: "delete" %>
              </li>
            <% else %>
              <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>